print("Getting to know you!\n")

Name = input("What's your name? ")
Food = input("What's your favorite food? ")
Music = input("What's yput favorite music? ")
Place = input("Where do you live? ")

print("\nYou are")
print(Name)
print("You're probably hungry for")
print(Food)
print("and you're definitely getting your groove on to")
print(Music)
print("living in the amazing")
print(Place)
